<?php
/**
 *  Defines the Section 106 Process module which defines
 *  a block presenting a flowchart of the Federal Preservation
 *  Section 106 Process.
 */

// Implements hook_theme ()
function section_106_process_theme () {
  return [
    'section_106_process' => ['variables' => []]
  ];
}

function embedViewInSection106ProcessBlock() {
  $view_content = views_embed_view('section_106_process', 'section_106_process');
  print render($view_content);
}