<?php
/**
 * @file
 * This file implements hook_block_view_alter
 * () which is responsible for attaching the
 * JS library.
 */

/**
 * Implements hook_block_view_alter ()
 *
 * Attaches the view_term_list_library to the 
 */
function view_term_list_block_view_alter (array &$build, \Drupal\Core\Block\BlockPluginInterface $block) {
  \Drupal::logger ('view_term_list')->notice ('[view_term_list_block_view_alter] build keys: <pre>' . print_r (array_keys ($build), true) . '</pre>');
  \Drupal::logger ('view_term_list')->notice ('[view_term_list_block_view_alter] build id: ' . $build ['#id']);
  $build ['#attached'] = array (
    'library' => array ('view_term_list/view_term_list_library')
  );
}
