<?php

// Implements hook_theme ()
function share_this_page_theme ($existing, $type, $theme, $path) {
  return [
    'share_this_page' => [
      'variables' => [
        'module_path' => base_path () . drupal_get_path('module', 'share_this_page'),
        'share_this_page_label' => \Drupal::config ('share_this_page.settings')->get ('share_this_page_label'),
        // Note: the following variables are set in the block build function which is called when the block is loaded.
        'page' => array (
          'url'   => null,
          'title' => null,
          'url_encoded_url'   => null,
          'url_encoded_title' => null
        )
      ]
    ]
  ];
}
