<?php
/**
 * @file
 */

// Implements hook_theme ()
function node_banner_theme () {
  return [
    'node_banner' => [
      'variables' => [
        'node_banner_banner_image_url' => '',
        'node_banner_overlay_fields' => []
      ]
    ]
  ];
}

/*
  Implements hook_page_attachements().

  Note: this function attaches the Node Banner
  library to every page.
*/
function node_banner_page_attachments(array &$attachments) {
  $attachments['#attached']['library'][] = 'node_banner/node_banner_library';
}
